#include "tkit/preprocessor/narg.hpp"

#define __TKIT_APPLY_1(fun, arg, ...) fun(arg)
#define __TKIT_APPLY_2(fun, arg, ...) fun(arg), __TKIT_APPLY_1(fun, __VA_ARGS__)
#define __TKIT_APPLY_3(fun, arg, ...) fun(arg), __TKIT_APPLY_2(fun, __VA_ARGS__)
#define __TKIT_APPLY_4(fun, arg, ...) fun(arg), __TKIT_APPLY_3(fun, __VA_ARGS__)
#define __TKIT_APPLY_5(fun, arg, ...) fun(arg), __TKIT_APPLY_4(fun, __VA_ARGS__)
#define __TKIT_APPLY_6(fun, arg, ...) fun(arg), __TKIT_APPLY_5(fun, __VA_ARGS__)
#define __TKIT_APPLY_7(fun, arg, ...) fun(arg), __TKIT_APPLY_6(fun, __VA_ARGS__)
#define __TKIT_APPLY_8(fun, arg, ...) fun(arg), __TKIT_APPLY_7(fun, __VA_ARGS__)
#define __TKIT_APPLY_9(fun, arg, ...) fun(arg), __TKIT_APPLY_8(fun, __VA_ARGS__)
#define __TKIT_APPLY_10(fun, arg, ...) fun(arg), __TKIT_APPLY_9(fun, __VA_ARGS__)
#define __TKIT_APPLY_11(fun, arg, ...) fun(arg), __TKIT_APPLY_10(fun, __VA_ARGS__)
#define __TKIT_APPLY_12(fun, arg, ...) fun(arg), __TKIT_APPLY_11(fun, __VA_ARGS__)
#define __TKIT_APPLY_13(fun, arg, ...) fun(arg), __TKIT_APPLY_12(fun, __VA_ARGS__)
#define __TKIT_APPLY_14(fun, arg, ...) fun(arg), __TKIT_APPLY_13(fun, __VA_ARGS__)
#define __TKIT_APPLY_15(fun, arg, ...) fun(arg), __TKIT_APPLY_14(fun, __VA_ARGS__)
#define __TKIT_APPLY_16(fun, arg, ...) fun(arg), __TKIT_APPLY_15(fun, __VA_ARGS__)
#define __TKIT_APPLY_17(fun, arg, ...) fun(arg), __TKIT_APPLY_16(fun, __VA_ARGS__)
#define __TKIT_APPLY_18(fun, arg, ...) fun(arg), __TKIT_APPLY_17(fun, __VA_ARGS__)
#define __TKIT_APPLY_19(fun, arg, ...) fun(arg), __TKIT_APPLY_18(fun, __VA_ARGS__)
#define __TKIT_APPLY_20(fun, arg, ...) fun(arg), __TKIT_APPLY_19(fun, __VA_ARGS__)
#define __TKIT_APPLY_21(fun, arg, ...) fun(arg), __TKIT_APPLY_20(fun, __VA_ARGS__)
#define __TKIT_APPLY_22(fun, arg, ...) fun(arg), __TKIT_APPLY_21(fun, __VA_ARGS__)
#define __TKIT_APPLY_23(fun, arg, ...) fun(arg), __TKIT_APPLY_22(fun, __VA_ARGS__)
#define __TKIT_APPLY_24(fun, arg, ...) fun(arg), __TKIT_APPLY_23(fun, __VA_ARGS__)
#define __TKIT_APPLY_25(fun, arg, ...) fun(arg), __TKIT_APPLY_24(fun, __VA_ARGS__)
#define __TKIT_APPLY_26(fun, arg, ...) fun(arg), __TKIT_APPLY_25(fun, __VA_ARGS__)
#define __TKIT_APPLY_27(fun, arg, ...) fun(arg), __TKIT_APPLY_26(fun, __VA_ARGS__)
#define __TKIT_APPLY_28(fun, arg, ...) fun(arg), __TKIT_APPLY_27(fun, __VA_ARGS__)
#define __TKIT_APPLY_29(fun, arg, ...) fun(arg), __TKIT_APPLY_28(fun, __VA_ARGS__)
#define __TKIT_APPLY_30(fun, arg, ...) fun(arg), __TKIT_APPLY_29(fun, __VA_ARGS__)
#define __TKIT_APPLY_31(fun, arg, ...) fun(arg), __TKIT_APPLY_30(fun, __VA_ARGS__)
#define __TKIT_APPLY_32(fun, arg, ...) fun(arg), __TKIT_APPLY_31(fun, __VA_ARGS__)
#define __TKIT_APPLY_33(fun, arg, ...) fun(arg), __TKIT_APPLY_32(fun, __VA_ARGS__)
#define __TKIT_APPLY_34(fun, arg, ...) fun(arg), __TKIT_APPLY_33(fun, __VA_ARGS__)
#define __TKIT_APPLY_35(fun, arg, ...) fun(arg), __TKIT_APPLY_34(fun, __VA_ARGS__)
#define __TKIT_APPLY_36(fun, arg, ...) fun(arg), __TKIT_APPLY_35(fun, __VA_ARGS__)
#define __TKIT_APPLY_37(fun, arg, ...) fun(arg), __TKIT_APPLY_36(fun, __VA_ARGS__)
#define __TKIT_APPLY_38(fun, arg, ...) fun(arg), __TKIT_APPLY_37(fun, __VA_ARGS__)
#define __TKIT_APPLY_39(fun, arg, ...) fun(arg), __TKIT_APPLY_38(fun, __VA_ARGS__)
#define __TKIT_APPLY_40(fun, arg, ...) fun(arg), __TKIT_APPLY_39(fun, __VA_ARGS__)
#define __TKIT_APPLY_41(fun, arg, ...) fun(arg), __TKIT_APPLY_40(fun, __VA_ARGS__)
#define __TKIT_APPLY_42(fun, arg, ...) fun(arg), __TKIT_APPLY_41(fun, __VA_ARGS__)
#define __TKIT_APPLY_43(fun, arg, ...) fun(arg), __TKIT_APPLY_42(fun, __VA_ARGS__)
#define __TKIT_APPLY_44(fun, arg, ...) fun(arg), __TKIT_APPLY_43(fun, __VA_ARGS__)
#define __TKIT_APPLY_45(fun, arg, ...) fun(arg), __TKIT_APPLY_44(fun, __VA_ARGS__)
#define __TKIT_APPLY_46(fun, arg, ...) fun(arg), __TKIT_APPLY_45(fun, __VA_ARGS__)
#define __TKIT_APPLY_47(fun, arg, ...) fun(arg), __TKIT_APPLY_46(fun, __VA_ARGS__)
#define __TKIT_APPLY_48(fun, arg, ...) fun(arg), __TKIT_APPLY_47(fun, __VA_ARGS__)
#define __TKIT_APPLY_49(fun, arg, ...) fun(arg), __TKIT_APPLY_48(fun, __VA_ARGS__)
#define __TKIT_APPLY_50(fun, arg, ...) fun(arg), __TKIT_APPLY_49(fun, __VA_ARGS__)
#define __TKIT_APPLY_51(fun, arg, ...) fun(arg), __TKIT_APPLY_50(fun, __VA_ARGS__)
#define __TKIT_APPLY_52(fun, arg, ...) fun(arg), __TKIT_APPLY_51(fun, __VA_ARGS__)
#define __TKIT_APPLY_53(fun, arg, ...) fun(arg), __TKIT_APPLY_52(fun, __VA_ARGS__)
#define __TKIT_APPLY_54(fun, arg, ...) fun(arg), __TKIT_APPLY_53(fun, __VA_ARGS__)
#define __TKIT_APPLY_55(fun, arg, ...) fun(arg), __TKIT_APPLY_54(fun, __VA_ARGS__)
#define __TKIT_APPLY_56(fun, arg, ...) fun(arg), __TKIT_APPLY_55(fun, __VA_ARGS__)
#define __TKIT_APPLY_57(fun, arg, ...) fun(arg), __TKIT_APPLY_56(fun, __VA_ARGS__)
#define __TKIT_APPLY_58(fun, arg, ...) fun(arg), __TKIT_APPLY_57(fun, __VA_ARGS__)
#define __TKIT_APPLY_59(fun, arg, ...) fun(arg), __TKIT_APPLY_58(fun, __VA_ARGS__)
#define __TKIT_APPLY_60(fun, arg, ...) fun(arg), __TKIT_APPLY_59(fun, __VA_ARGS__)
#define __TKIT_APPLY_61(fun, arg, ...) fun(arg), __TKIT_APPLY_60(fun, __VA_ARGS__)
#define __TKIT_APPLY_62(fun, arg, ...) fun(arg), __TKIT_APPLY_61(fun, __VA_ARGS__)
#define __TKIT_APPLY_63(fun, arg, ...) fun(arg), __TKIT_APPLY_62(fun, __VA_ARGS__)
#define __TKIT_APPLY_64(fun, arg, ...) fun(arg), __TKIT_APPLY_63(fun, __VA_ARGS__)

#define __TKIT_APPLY_GROUPED_1(fun, arg, ...) fun arg
#define __TKIT_APPLY_GROUPED_2(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_1(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_3(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_2(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_4(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_3(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_5(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_4(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_6(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_5(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_7(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_6(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_8(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_7(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_9(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_8(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_10(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_9(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_11(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_10(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_12(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_11(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_13(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_12(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_14(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_13(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_15(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_14(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_16(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_15(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_17(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_16(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_18(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_17(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_19(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_18(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_20(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_19(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_21(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_20(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_22(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_21(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_23(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_22(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_24(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_23(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_25(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_24(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_26(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_25(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_27(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_26(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_28(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_27(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_29(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_28(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_30(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_29(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_31(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_30(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_32(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_31(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_33(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_32(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_34(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_33(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_35(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_34(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_36(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_35(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_37(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_36(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_38(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_37(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_39(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_38(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_40(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_39(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_41(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_40(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_42(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_41(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_43(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_42(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_44(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_43(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_45(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_44(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_46(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_45(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_47(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_46(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_48(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_47(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_49(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_48(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_50(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_49(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_51(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_50(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_52(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_51(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_53(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_52(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_54(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_53(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_55(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_54(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_56(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_55(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_57(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_56(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_58(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_57(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_59(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_58(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_60(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_59(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_61(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_60(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_62(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_61(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_63(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_62(fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_64(fun, arg, ...) fun arg, __TKIT_APPLY_GROUPED_63(fun, __VA_ARGS__)

#define __TKIT_APPLY_SELECTOR(n) __TKIT_APPLY_##n
#define __TKIT_APPLY_DISPATCH(n, ...) __TKIT_APPLY_SELECTOR(n)(__VA_ARGS__)

#define __TKIT_APPLY_GROUPED_SELECTOR(n) __TKIT_APPLY_GROUPED_##n
#define __TKIT_APPLY_GROUPED_DISPATCH(n, ...) __TKIT_APPLY_GROUPED_SELECTOR(n)(__VA_ARGS__)

#define TKIT_APPLY(fun, ...) __TKIT_APPLY_DISPATCH(TKIT_NARG(__VA_ARGS__), fun, __VA_ARGS__)
#define TKIT_APPLY_GROUPED(fun, ...) __TKIT_APPLY_GROUPED_DISPATCH(TKIT_NARG(__VA_ARGS__), fun, __VA_ARGS__)