#include "tkit/preprocessor/narg.hpp"

#define __TKIT_APPLY_1(p_Fun, p_Arg, ...) p_Fun(p_Arg)
#define __TKIT_APPLY_2(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_1(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_3(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_2(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_4(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_3(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_5(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_4(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_6(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_5(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_7(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_6(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_8(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_7(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_9(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_8(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_10(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_9(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_11(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_10(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_12(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_11(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_13(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_12(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_14(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_13(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_15(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_14(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_16(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_15(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_17(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_16(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_18(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_17(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_19(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_18(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_20(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_19(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_21(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_20(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_22(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_21(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_23(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_22(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_24(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_23(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_25(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_24(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_26(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_25(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_27(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_26(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_28(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_27(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_29(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_28(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_30(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_29(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_31(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_30(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_32(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_31(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_33(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_32(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_34(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_33(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_35(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_34(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_36(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_35(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_37(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_36(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_38(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_37(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_39(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_38(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_40(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_39(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_41(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_40(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_42(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_41(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_43(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_42(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_44(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_43(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_45(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_44(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_46(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_45(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_47(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_46(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_48(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_47(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_49(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_48(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_50(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_49(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_51(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_50(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_52(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_51(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_53(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_52(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_54(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_53(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_55(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_54(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_56(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_55(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_57(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_56(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_58(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_57(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_59(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_58(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_60(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_59(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_61(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_60(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_62(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_61(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_63(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_62(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_64(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_63(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_65(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_64(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_66(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_65(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_67(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_66(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_68(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_67(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_69(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_68(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_70(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_69(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_71(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_70(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_72(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_71(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_73(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_72(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_74(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_73(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_75(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_74(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_76(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_75(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_77(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_76(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_78(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_77(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_79(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_78(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_80(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_79(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_81(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_80(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_82(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_81(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_83(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_82(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_84(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_83(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_85(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_84(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_86(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_85(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_87(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_86(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_88(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_87(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_89(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_88(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_90(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_89(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_91(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_90(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_92(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_91(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_93(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_92(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_94(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_93(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_95(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_94(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_96(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_95(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_97(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_96(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_98(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_97(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_99(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_98(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_100(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_99(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_101(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_100(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_102(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_101(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_103(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_102(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_104(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_103(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_105(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_104(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_106(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_105(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_107(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_106(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_108(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_107(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_109(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_108(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_110(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_109(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_111(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_110(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_112(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_111(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_113(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_112(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_114(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_113(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_115(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_114(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_116(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_115(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_117(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_116(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_118(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_117(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_119(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_118(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_120(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_119(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_121(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_120(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_122(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_121(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_123(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_122(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_124(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_123(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_125(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_124(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_126(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_125(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_127(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_126(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_128(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_127(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_129(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_128(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_130(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_129(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_131(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_130(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_132(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_131(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_133(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_132(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_134(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_133(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_135(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_134(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_136(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_135(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_137(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_136(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_138(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_137(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_139(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_138(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_140(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_139(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_141(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_140(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_142(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_141(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_143(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_142(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_144(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_143(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_145(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_144(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_146(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_145(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_147(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_146(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_148(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_147(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_149(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_148(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_150(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_149(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_151(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_150(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_152(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_151(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_153(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_152(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_154(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_153(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_155(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_154(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_156(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_155(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_157(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_156(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_158(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_157(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_159(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_158(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_160(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_159(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_161(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_160(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_162(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_161(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_163(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_162(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_164(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_163(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_165(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_164(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_166(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_165(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_167(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_166(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_168(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_167(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_169(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_168(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_170(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_169(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_171(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_170(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_172(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_171(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_173(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_172(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_174(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_173(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_175(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_174(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_176(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_175(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_177(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_176(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_178(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_177(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_179(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_178(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_180(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_179(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_181(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_180(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_182(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_181(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_183(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_182(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_184(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_183(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_185(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_184(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_186(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_185(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_187(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_186(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_188(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_187(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_189(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_188(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_190(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_189(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_191(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_190(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_192(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_191(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_193(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_192(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_194(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_193(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_195(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_194(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_196(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_195(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_197(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_196(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_198(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_197(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_199(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_198(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_200(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_199(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_201(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_200(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_202(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_201(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_203(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_202(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_204(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_203(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_205(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_204(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_206(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_205(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_207(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_206(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_208(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_207(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_209(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_208(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_210(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_209(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_211(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_210(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_212(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_211(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_213(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_212(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_214(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_213(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_215(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_214(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_216(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_215(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_217(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_216(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_218(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_217(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_219(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_218(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_220(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_219(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_221(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_220(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_222(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_221(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_223(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_222(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_224(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_223(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_225(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_224(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_226(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_225(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_227(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_226(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_228(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_227(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_229(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_228(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_230(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_229(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_231(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_230(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_232(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_231(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_233(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_232(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_234(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_233(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_235(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_234(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_236(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_235(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_237(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_236(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_238(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_237(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_239(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_238(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_240(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_239(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_241(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_240(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_242(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_241(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_243(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_242(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_244(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_243(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_245(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_244(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_246(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_245(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_247(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_246(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_248(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_247(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_249(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_248(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_250(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_249(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_251(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_250(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_252(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_251(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_253(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_252(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_254(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_253(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_255(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_254(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_256(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_255(p_Fun, __VA_ARGS__)

#define __TKIT_APPLY_GROUPED_1(p_Fun, p_Arg, ...) p_Fun p_Arg
#define __TKIT_APPLY_GROUPED_2(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_1(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_3(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_2(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_4(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_3(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_5(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_4(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_6(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_5(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_7(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_6(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_8(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_7(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_9(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_8(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_10(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_9(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_11(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_10(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_12(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_11(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_13(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_12(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_14(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_13(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_15(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_14(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_16(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_15(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_17(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_16(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_18(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_17(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_19(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_18(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_20(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_19(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_21(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_20(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_22(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_21(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_23(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_22(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_24(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_23(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_25(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_24(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_26(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_25(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_27(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_26(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_28(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_27(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_29(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_28(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_30(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_29(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_31(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_30(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_32(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_31(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_33(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_32(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_34(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_33(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_35(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_34(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_36(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_35(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_37(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_36(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_38(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_37(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_39(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_38(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_40(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_39(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_41(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_40(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_42(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_41(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_43(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_42(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_44(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_43(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_45(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_44(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_46(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_45(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_47(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_46(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_48(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_47(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_49(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_48(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_50(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_49(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_51(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_50(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_52(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_51(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_53(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_52(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_54(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_53(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_55(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_54(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_56(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_55(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_57(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_56(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_58(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_57(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_59(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_58(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_60(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_59(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_61(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_60(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_62(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_61(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_63(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_62(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_64(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_63(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_65(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_64(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_66(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_65(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_67(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_66(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_68(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_67(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_69(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_68(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_70(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_69(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_71(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_70(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_72(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_71(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_73(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_72(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_74(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_73(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_75(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_74(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_76(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_75(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_77(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_76(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_78(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_77(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_79(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_78(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_80(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_79(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_81(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_80(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_82(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_81(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_83(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_82(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_84(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_83(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_85(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_84(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_86(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_85(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_87(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_86(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_88(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_87(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_89(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_88(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_90(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_89(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_91(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_90(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_92(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_91(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_93(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_92(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_94(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_93(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_95(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_94(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_96(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_95(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_97(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_96(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_98(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_97(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_99(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_98(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_100(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_99(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_101(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_100(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_102(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_101(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_103(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_102(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_104(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_103(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_105(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_104(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_106(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_105(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_107(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_106(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_108(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_107(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_109(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_108(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_110(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_109(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_111(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_110(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_112(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_111(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_113(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_112(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_114(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_113(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_115(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_114(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_116(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_115(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_117(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_116(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_118(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_117(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_119(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_118(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_120(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_119(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_121(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_120(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_122(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_121(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_123(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_122(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_124(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_123(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_125(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_124(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_126(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_125(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_127(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_126(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_128(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_127(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_129(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_128(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_130(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_129(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_131(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_130(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_132(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_131(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_133(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_132(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_134(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_133(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_135(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_134(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_136(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_135(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_137(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_136(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_138(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_137(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_139(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_138(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_140(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_139(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_141(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_140(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_142(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_141(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_143(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_142(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_144(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_143(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_145(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_144(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_146(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_145(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_147(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_146(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_148(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_147(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_149(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_148(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_150(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_149(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_151(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_150(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_152(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_151(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_153(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_152(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_154(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_153(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_155(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_154(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_156(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_155(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_157(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_156(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_158(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_157(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_159(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_158(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_160(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_159(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_161(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_160(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_162(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_161(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_163(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_162(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_164(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_163(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_165(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_164(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_166(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_165(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_167(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_166(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_168(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_167(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_169(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_168(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_170(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_169(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_171(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_170(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_172(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_171(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_173(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_172(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_174(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_173(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_175(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_174(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_176(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_175(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_177(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_176(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_178(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_177(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_179(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_178(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_180(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_179(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_181(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_180(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_182(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_181(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_183(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_182(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_184(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_183(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_185(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_184(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_186(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_185(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_187(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_186(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_188(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_187(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_189(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_188(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_190(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_189(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_191(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_190(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_192(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_191(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_193(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_192(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_194(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_193(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_195(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_194(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_196(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_195(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_197(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_196(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_198(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_197(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_199(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_198(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_200(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_199(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_201(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_200(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_202(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_201(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_203(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_202(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_204(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_203(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_205(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_204(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_206(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_205(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_207(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_206(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_208(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_207(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_209(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_208(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_210(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_209(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_211(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_210(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_212(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_211(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_213(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_212(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_214(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_213(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_215(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_214(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_216(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_215(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_217(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_216(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_218(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_217(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_219(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_218(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_220(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_219(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_221(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_220(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_222(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_221(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_223(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_222(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_224(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_223(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_225(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_224(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_226(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_225(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_227(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_226(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_228(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_227(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_229(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_228(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_230(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_229(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_231(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_230(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_232(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_231(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_233(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_232(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_234(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_233(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_235(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_234(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_236(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_235(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_237(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_236(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_238(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_237(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_239(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_238(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_240(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_239(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_241(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_240(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_242(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_241(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_243(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_242(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_244(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_243(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_245(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_244(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_246(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_245(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_247(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_246(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_248(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_247(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_249(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_248(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_250(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_249(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_251(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_250(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_252(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_251(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_253(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_252(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_254(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_253(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_255(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_254(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_256(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_255(p_Fun, __VA_ARGS__)

#define __TKIT_APPLY_SELECTOR(p_N) __TKIT_APPLY_##p_N
#define __TKIT_APPLY_DISPATCH(p_N, ...) __TKIT_APPLY_SELECTOR(p_N)(__VA_ARGS__)

#define __TKIT_APPLY_GROUPED_SELECTOR(p_N) __TKIT_APPLY_GROUPED_##p_N
#define __TKIT_APPLY_GROUPED_DISPATCH(p_N, ...) __TKIT_APPLY_GROUPED_SELECTOR(p_N)(__VA_ARGS__)

#define TKIT_APPLY(p_Fun, ...) __TKIT_APPLY_DISPATCH(TKIT_NARG(__VA_ARGS__), p_Fun, __VA_ARGS__)
#define TKIT_APPLY_GROUPED(p_Fun, ...) __TKIT_APPLY_GROUPED_DISPATCH(TKIT_NARG(__VA_ARGS__), p_Fun, __VA_ARGS__)