#include "tkit/preprocessor/narg.hpp"

#define __TKIT_APPLY_1(p_Fun, p_Arg, ...) p_Fun(p_Arg)
#define __TKIT_APPLY_2(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_1(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_3(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_2(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_4(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_3(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_5(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_4(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_6(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_5(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_7(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_6(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_8(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_7(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_9(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_8(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_10(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_9(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_11(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_10(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_12(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_11(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_13(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_12(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_14(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_13(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_15(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_14(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_16(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_15(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_17(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_16(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_18(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_17(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_19(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_18(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_20(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_19(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_21(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_20(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_22(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_21(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_23(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_22(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_24(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_23(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_25(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_24(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_26(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_25(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_27(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_26(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_28(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_27(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_29(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_28(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_30(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_29(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_31(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_30(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_32(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_31(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_33(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_32(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_34(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_33(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_35(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_34(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_36(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_35(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_37(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_36(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_38(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_37(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_39(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_38(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_40(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_39(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_41(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_40(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_42(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_41(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_43(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_42(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_44(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_43(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_45(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_44(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_46(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_45(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_47(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_46(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_48(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_47(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_49(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_48(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_50(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_49(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_51(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_50(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_52(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_51(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_53(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_52(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_54(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_53(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_55(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_54(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_56(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_55(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_57(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_56(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_58(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_57(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_59(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_58(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_60(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_59(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_61(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_60(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_62(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_61(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_63(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_62(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_64(p_Fun, p_Arg, ...) p_Fun(p_Arg), __TKIT_APPLY_63(p_Fun, __VA_ARGS__)

#define __TKIT_APPLY_GROUPED_1(p_Fun, p_Arg, ...) p_Fun p_Arg
#define __TKIT_APPLY_GROUPED_2(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_1(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_3(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_2(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_4(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_3(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_5(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_4(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_6(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_5(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_7(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_6(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_8(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_7(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_9(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_8(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_10(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_9(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_11(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_10(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_12(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_11(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_13(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_12(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_14(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_13(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_15(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_14(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_16(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_15(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_17(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_16(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_18(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_17(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_19(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_18(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_20(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_19(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_21(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_20(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_22(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_21(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_23(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_22(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_24(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_23(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_25(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_24(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_26(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_25(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_27(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_26(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_28(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_27(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_29(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_28(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_30(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_29(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_31(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_30(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_32(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_31(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_33(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_32(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_34(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_33(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_35(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_34(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_36(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_35(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_37(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_36(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_38(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_37(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_39(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_38(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_40(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_39(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_41(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_40(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_42(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_41(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_43(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_42(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_44(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_43(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_45(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_44(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_46(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_45(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_47(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_46(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_48(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_47(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_49(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_48(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_50(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_49(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_51(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_50(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_52(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_51(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_53(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_52(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_54(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_53(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_55(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_54(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_56(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_55(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_57(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_56(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_58(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_57(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_59(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_58(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_60(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_59(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_61(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_60(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_62(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_61(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_63(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_62(p_Fun, __VA_ARGS__)
#define __TKIT_APPLY_GROUPED_64(p_Fun, p_Arg, ...) p_Fun p_Arg, __TKIT_APPLY_GROUPED_63(p_Fun, __VA_ARGS__)

#define __TKIT_APPLY_SELECTOR(p_N) __TKIT_APPLY_##p_N
#define __TKIT_APPLY_DISPATCH(p_N, ...) __TKIT_APPLY_SELECTOR(p_N)(__VA_ARGS__)

#define __TKIT_APPLY_GROUPED_SELECTOR(p_N) __TKIT_APPLY_GROUPED_##p_N
#define __TKIT_APPLY_GROUPED_DISPATCH(p_N, ...) __TKIT_APPLY_GROUPED_SELECTOR(p_N)(__VA_ARGS__)

#define TKIT_APPLY(p_Fun, ...) __TKIT_APPLY_DISPATCH(TKIT_NARG(__VA_ARGS__), p_Fun, __VA_ARGS__)
#define TKIT_APPLY_GROUPED(p_Fun, ...) __TKIT_APPLY_GROUPED_DISPATCH(TKIT_NARG(__VA_ARGS__), p_Fun, __VA_ARGS__)